FROM alpine/git as Build

RUN mkdir -p /app/leonardo
RUN git clone --depth=1 https://github.com/jolie/leonardo.git /app/leonardo
RUN rm -rf /app/leonardo/docker
RUN rm -rf /app/leonardo/.git

# Start from scratch, copy leonardo
FROM jolielang/jolie:jre
WORKDIR /
COPY --from=Build /app /app

WORKDIR /app/leonardo/cmd/leonardo

CMD ["jolie","main.ol"]
